#!/usr/bin/env bash
# configures a new Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo systemctl start nginx
