#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo systemctl restart nginx
