#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains
# the string Ceci n'est pas une page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
