#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
# In between each iteration of the loop, add a sleep 2.
c=1
while [ $c ]
do
    echo "To infinity and beyond"
    sleep 2
done
