#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times,
# but for the 9th iteration, displays Holberton School
# and then Hi on a new line.
c=1
while [[ $c -le 10 ]]
do
    if [[ $c -eq 10 ]]
    then
	echo "Hi"
	c=$((c+1))
    fi
    echo "Holberton School"
    c=$((c+1))
done
