#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:
# displays "bad luck" for the 4th loop iteration
# displays "good luck" for the 8th loop iteration
# displays "Holberton School" for the other iterations
# use while, if, elif and else
c=1
while [[ $c -le 10 ]]
do
    if [[ $c -eq 4 ]]
    then
	echo "bad luck"
	c=$((c+1))
    elif [[ $c -eq 8 ]]
    then
	echo "good luck"
	c=$((c+1))
    else
	echo "Holberton School"
	c=$((c+1))
    fi
done
