#!/usr/bin/env bash
# Share your SSH client configuration in your answer file.
# * Your SSH client configuration must be configured to use the
# private key ~/.ssh/holberton
# * Your SSH client configuration must be configured to refuse
# to authenticate using a password
HOST 35.231.65.220
     IdentityFile ~/.ssh/holberton
     PasswordAuthentication no
